lockdownTimerDuration: 60
spawnerMiningCost: 100
maxSpawnerChunksPerFaction: 10
raidProgressMessages:
  - You are being raided#10
  - You are still being raided#30
  - You are no longer being raided#60
lockdownCommandBlacklist:
  - /printer
  - /gb
  
messages:
  breakSpawnerSuccess: 'You have broken the spawner for %cost'
  breakSpawnerFail: 'You have insufficient funds to break this spawner %cost%'
  failCommandWhileLockdown: 'You cannot perform this command while in lockdown %command%'
  spawnerPlaceOutsideClaim: 'You cannot place a spawner outside a spawnerchunk'
  spawnerPlaceNearWater: 'You cannot place a spawner within 7 blocks of water'
  claimSpawnerChunk: 'You have successfully claimed a spawner chunk at %location%'
  failClaimSpawnerChunkNearbyFaction: 'There is a spawner chunk belonging to another faction within a 15 chunk radius'
  failClaimSpawnerChunkAlreadyOwned: 'This chunk is already claimed as a spawner chunk'
  failClaimSpawnerChunkMaxChunks: 'You do not have any more spawnerchunks available'
  failClaimSpawnerChunkNotOwned: 'You cannot claim a spawnerchunk in a chunk that is not owned by you'
  failClaimSpawnerChunkPermissions: 'You must be moderator or leader to claim a spawnerchunk'
  failNotInFaction: 'You are not in a faction'
  unclaimSpawnerChunk: 'You have unlclaimed a spawnerchunk at %location%'
  failUnclaimSpawnerChunkNotOwned: 'You cannot unclaim a spawnerchunk that is not owned by you'
  failUnclaimSpawnerChunkNoChunks: 'You have no spawnerchunks claimed'
  failUnclaimSpawnerChunkPermissions: 'You must be moderator or leader to unclaim a spawnerchunk'
  lockdownInformation: 'Lockdown time remaining: %time%'
  lockdownNotActive: 'Your faction is not under lockdown'
  lockdownActive: 'Your faction is now under lockdown'
  lockdownEnd: 'Your faction is no longer under lockdown'
  lockdownNoChunks: 'Your faction does not have any spawnerchunks claimed'
  